#!/usr/bin/env bash

JSON=$2

COLLECTION_NAME=$(echo ${JSON} | jq -r '.collections[0].name')
COLLECTION_PATH=$(echo ${JSON} | jq -r '.collections[0].path')

/work/anserini/solrini/bin/solr create -c ${COLLECTION_NAME} -n anserini -force

sh /work/anserini/target/appassembler/bin/IndexCollection \
    -collection TrecCollection -generator JsoupGenerator \
    -threads $(nproc) \
    -solr -solr.batch 1000 -solr.commitWithin 300 -solr.index ${COLLECTION_NAME} -solr.zkUrl localhost:9983 \
    -input ${COLLECTION_PATH} \
    -storePositions -storeDocvectors -storeRawDocs

# Stop Solr
/work/anserini/solrini/bin/solr stop -all