#!/usr/bin/env bash

JSON=$2

# Args from jig
SOLR_MEMORY=$(echo ${JSON} | jq -r '.opts.solr_memory')
[[ ${SOLR_MEMORY} = "null" ]] && SOLR_MEMORY=8G

SOLR_VERSION=$(echo ${JSON} | jq -r '.opts.solr_version')
[[ ${SOLR_VERSION} = "null" ]] && SOLR_VERSION=8.0.0

# Clone Anserini
git clone https://github.com/castorini/anserini.git --branch=anserini-0.5.1 && cd anserini

# Build Anserini
mvn clean package appassembler:assemble -DskipTests

# Download Solr
wget https://archive.apache.org/dist/lucene/solr/${SOLR_VERSION}/solr-${SOLR_VERSION}.tgz

# Extract archive
mkdir solrini && tar -zxvf solr*.tgz -C solrini --strip-components=1

# Start Solr
solrini/bin/solr start -c -m ${SOLR_MEMORY} -force

# Bootstrap Solr with anserini configsets.
pushd src/main/resources/solr && ./solr.sh ../../../../solrini localhost:9983 && popd
